[project]
name = "reci-checker"
version = "0.2.0"
description = "Verificador de conformidade de manuscritos - CLI + leitura DOCX/PDF"
requires-python = ">=3.11"
dependencies = [
  "python-docx>=1.0.0",
  "pymupdf>=1.24.0"
]

[tool.pytest.ini_options]
addopts = "-q"
